### ISSUE TITLE
Change Name to Bitcoin Private (Rebrand)

### ISSUE THREAD

**Issue by heyrhett** [BTCPrivate/BitcoinPrivate#1]
Replace instances of Zclassic with Bitcoin Private where applicable

**Comment by Hohhle** [comment]
Gotta start somewhere. I might as well do this.

**Comment by skyl** [comment]
Is the goal to maintain the Zclassic fork and this fork or just this fork? Do you have a post what the goal and which chain(s) will be used, how chain splits will happen, etc?

**Comment by heyrhett** [comment]
Closed with https://github.com/BTCPrivate/BitcoinPrivate/pull/2
