### ISSUE TITLE
Mac Installation Caveats

### ISSUE THREAD

**Issue by ch4ot1c** [BTCPrivate/BitcoinPrivate#10]
In the installation steps for Mac, some commands are only partially working:

`nproc` doesn't exist on my instance of MacOS (10.12.6). I replaced it with `sysctl -n hw.physicalcpu`, and was able to build without the error that had appeared: `clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable`.

I also get a slew of these upon (successfully) building:
`ld: warning: object file (/Users/Jon/BitcoinPrivate/depends/x86_64-apple-darwin16.7.0/lib/libdb_cxx-6.2.a(mp_mvcc.o)) was built for newer OSX version (10.12) than being linked (10.7)`

When running fetch-params.sh:
`./zcutil/fetch-params.sh: line 62: flock: command not found` appears, but it succeeds anyway.
Perhaps `https://github.com/discoteq/flock`? Or is there another native approach we'd prefer?

Built & started the node successfully, in the end:
```
Thank you for running a Bitcoin Private node!
You're helping to strengthen the network and contributing to a social good :)
```

**Comment by heyrhett** [comment]
merged!
