### ISSUE TITLE
Error reading configuration file: Missing btcprivate.conf

### ISSUE THREAD

**Issue by VERTlG0** [BTCPrivate/BitcoinPrivate#100]
when trying to run btcp-cli.exe It failes with trying to find btcprivate.conf creating an empty one doesnt solve it.. or making one with just "-rpcuser=x -rpcpassword=x" and it still couldnt see the file and gave the same error message.

**Comment by VERTlG0** [comment]
Closing issue. I was wrong about the location of btcprivate.conf and now have it in the right spot.

Solution: touch /mnt/c/Users/Vertigo/AppData/Romaing/BTCPrivate
OR
cp contrib/debian/examples/btcprivate.conf /mnt/c/Users/Vertigo/AppData/Roaming/BTCPrivate/

**Comment by buzztiaan** [comment]
or ~/.btcprivate/btcprivate.conf
