### ISSUE TITLE
Error: Cannot find the Bitcoin Private network parameters

### ISSUE THREAD

**Issue by VERTlG0** [BTCPrivate/BitcoinPrivate#101]
Built with Linux Subsystem for Windows10 64bit.

cf@z170x-WIN10:/mnt/c/btcp/BTCPrivate/home/cf/BitcoinPrivate/depends/x86_64-w64-mingw32/bin$ ./btcpd.exe
Error: Cannot find the Bitcoin Private network parameters in the following directory:
"C:\Users\Vertigo\AppData\Roaming\ZcashParams"
Please run 'zcash-fetch-params' or './btcputil/fetch-params.sh' and then restart.

I already ran zcash-fetch-params which downloaded a sprout.verifying.key file, re-ran ./btcpd.exe and same error happens again each time.

**Comment by ch4ot1c** [comment]
Sorry - their url was removed! Try the latest version. https://github.com/BTCPrivate/BitcoinPrivate/commit/f4946632b0f6cb6b0e6f7511355ca19a889e04e6 has the fix
