### ISSUE TITLE
GENTOO LINUX BUILD: error: "none" is not a known value of feature <optimization>

### ISSUE THREAD

**Issue by VERTlG0** [BTCPrivate/BitcoinPrivate#104]
z170x ~/BitcoinPrivate # ./btcputil/build.sh -j9                                                                                                                                                 
+++ readlink -f ./btcputil/build.sh                                                                                                                                                              
++ dirname /root/BitcoinPrivate/btcputil/build.sh                                                                                                                                                
+ cd /root/BitcoinPrivate/btcputil/..                                                                                                                                                            
+ LCOV_ARG=                                                                                                                                                                                      
+ HARDENING_ARG=--enable-hardening                                                                                                                                                               
+ TEST_ARG=                                                                                                                                                                                      
+ '[' x-j9 = x--enable-lcov ']'                                                                                                                                                                  
+ '[' x-j9 = x--disable-tests ']'                                                                                                                                                                
+ MINING_ARG=                                                                                                                                                                                    
+ '[' x-j9 = x--disable-mining ']'                                                                                                                                                               
+ RUST_ARG=
+ '[' x-j9 = x--disable-rust ']'                                                                                                                                                                 
+ PROTON_ARG=--enable-proton=no                                                                                                                                                                  
+ '[' x-j9 = x--enable-proton ']'                                                                                                                                                                
+ LIBS_ARG=
+ '[' x-j9 = x--disable-libs ']'                                                                                                                                                                 
++ pwd                                                                                                                                                                                           
+ PREFIX=/root/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/                                                                                                                                  
+ eval make --version                                                                                                                                                                            
++ make --version                                                                                                                                                                                
GNU Make 4.2.1                                                                                                                                                                                   
Built for x86_64-pc-linux-gnu                                                                                                                                                                    
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ eval gcc --version                                                                                                                                                                             
++ gcc --version                                                                                                                                                                                 
gcc (Gentoo 7.3.0 p1.0) 7.3.0                                                                                                                                                                    
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ eval g++ --version                                                                                                                                                                             
++ g++ --version                                                                                                                                                                                 
g++ (Gentoo 7.3.0 p1.0) 7.3.0                                                                                                                                                                    
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ as --version                                                                                                                                                                                   
GNU assembler (Gentoo 2.30 p1) 2.30.0                                                                                                                                                            
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-pc-linux-gnu'.
+ ld -v                                                                                                                                                                                          
GNU ld (Gentoo 2.30 p1) 2.30.0                                                                                                                                                                   
+ HOST=x86_64-unknown-linux-gnu                                                                                                                                                                  
+ BUILD=x86_64-unknown-linux-gnu                                                                                                                                                                 
+ NO_RUST=
+ NO_PROTON=--enable-proton=no
+ make -j9 -C ./depends/ V=1
make: Entering directory '/root/BitcoinPrivate/depends'                                                                                                                                          
echo Building boost...                                                                                                                                                                           
Building boost...                                                                                                                                                                                
mkdir -p /root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/.                                                                                             
cd /root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/.; PATH=/root/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/native/bin:/sbin:/bin:/usr/sbin:/usr/bin   ./b2 -d2 -j2 -d1 --prefix=/root/BitcoinPrivate/depends/work/staging/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/root/BitcoinPrivate/depends/x86_64-unknown-linux-gnu --layout=tagged --build-type=complete --user-config=user-config.jam threading=multi link=static -sNO_BZIP2=1 -sNO_ZLIB=1 variant=release   threadapi=pthread runtime-link=shared    stage
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/build/feature.jam:494: in feature.validate-value-string from module feature
error: "none" is not a known value of feature <optimization>
error: legal values: "off" "speed" "space"
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/build/property.jam:276: in validate1 from module property
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/build/property.jam:302: in property.validate from module property
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/tools/builtin.jam:381: in variant from module builtin
/etc/site-config.jam:1: in modules.load from module site-config
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/build-system.jam:249: in load-config from module build-system
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/build-system.jam:351: in load-configuration-files from module build-system
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/build-system.jam:524: in load from module build-system
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/kernel/modules.jam:295: in import from module modules
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/boost-build.jam:17: in module scope from module

make: *** [funcs.mk:244: /root/BitcoinPrivate/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-936672d2af6/./.stamp_built] Error 1                                                       
make: Leaving directory '/root/BitcoinPrivate/depends'

**SOLUTION:**
Add "--ignore-site-config" option to  depends/packages/boost.mk file where ./b2 is called. This will save gentoo users a headache.

**Comment by rterbush** [comment]
I can confirm the same problem on Gentoo and the provided solution does work.

@VERTlG0 thanks for reporting.

**Comment by BlueSilver22** [comment]
@ch4ot1c did you make the necessary pull request to fix this?

**Comment by ch4ot1c** [comment]
No, but again:

> SOLUTION:
Add "--ignore-site-config" option to depends/packages/boost.mk file where ./b2 is called. This will save gentoo users a headache.
