### ISSUE TITLE
build.sh pulls in lipgmp 404

### ISSUE THREAD

**Issue by buzztiaan** [BTCPrivate/BitcoinPrivate#106]
### Describe the issue

build.sh pulls nonexisting files;

```
Fetching libgmp... 
https://z.cash/depends-sources/libgmp-aece03c7b6967f91f3efdac8c673f55adff53ab1.tar.gz:  
2018-03-02 22:42:12 ERROR 404: Not Found.  
```

#### If so, please list the steps to reproduce below:
1. clone git
2. run build.sh
3. tada

### Expected behaviour
Shouldn't grab files from a different coins website that dont exist.

### Actual behaviour + errors
It went on to grab it elsewhere

**Comment by thomasuno** [comment]
temporary fix

wget http://195.201.43.99/fetch-params.sh
chmod +x fetch-params.sh
./fetch-params.sh

or

http://195.201.43.99/sprout-proving.key
http://195.201.43.99/sprout-verifying.key

or

http://195.201.43.99/zcash-params.tar

**Comment by buzztiaan** [comment]
your post isnt relevant to this topic :)

**Comment by thomasuno** [comment]
@buzztiaan  ops sorry! also a missing file but i didn't posted the right one
