### ISSUE TITLE
./btcputil/fetch-params.sh doesnt fetch jack sh**

### ISSUE THREAD

**Issue by buzztiaan** [BTCPrivate/BitcoinPrivate#108]
Eh, i think the title is self explanatory.

**Comment by thomasuno** [comment]
temporary fix

wget http://195.201.43.99/fetch-params.sh
chmod +x fetch-params.sh
./fetch-params.sh

or

http://195.201.43.99/sprout-proving.key
http://195.201.43.99/sprout-verifying.key

**Comment by buzztiaan** [comment]
right, i already had them from a ZEC and ZCL node, but tnx :D

**Comment by ch4ot1c** [comment]
Updated: https://github.com/BTCPrivate/BitcoinPrivate/commit/23954cd6816d7ae3d8c2d9e7ff69dc5ffcb64689

This is a trusted resource.
