### ISSUE TITLE
How can i get the BTCP ?

### ISSUE THREAD

**Issue by sedarat** [BTCPrivate/BitcoinPrivate#112]
I have some ZCL in the tradesatodhi .....
Where can I check that the BTCP has arrived ?
Please help me ....

**Comment by shwimmy** [comment]
The forking process has started! It will be finished in the next 12-36 hours, after which you can claim your #BTCP. See instructions on how to join the forking process here (Linux Users Only): https://goo.gl/RgQiCm

**Comment by sedarat** [comment]
Thank you very much my friend

**Comment by shwimmy** [comment]
You are welcome.  I was just reposting the news I had just read.

**Comment by Raphael1994** [comment]
I have some zcl in cryptopia 
How do I get bitcoin private?

**Comment by ch4ot1c** [comment]
Consult with the exchange's instructions and timeline - should be fairly soon.
