### ISSUE TITLE
buy ZCL

### ISSUE THREAD

**Issue by salimizadeh** [BTCPrivate/BitcoinPrivate#116]
3 Questions:
If I buy ZCL now, Will I get BTCP?
In this case, Will ZCL be unusable?
Which exchanges support this fork?
Best regards.

**Comment by Ultanium** [comment]
It was my understanding that no, they will not trade it out, so anything after the snapshot you may want to sell or abandon.

**Comment by ocarinaz64** [comment]
The snapshot has already taken place.  ZCL is still useable, and will have whatever value people decide for it.  Rhett did say that he wasn't going to do any more work with the project.  But no, you won't get any BTCP if you buy ZCL now.  The split is over and done with.  If you want BTCP now, you have to trade for it.

**Comment by ch4ot1c** [comment]
No, the snapshot occurred already as stated on https://btcprivate.org . ZCL will continue to exist as a blockchain, tradeable and usable.
