### ISSUE TITLE
Working ZClassic Wallet Download on Website

### ISSUE THREAD

**Issue by Teecoy** [BTCPrivate/BitcoinPrivate#12]
I'm having problems downloading the Wallet for Windows, off of the website. I've seen some videos, not on the website, on how to do it. If we can get confirmation that those are safe to follow, and add them to the website, I'll pitch in 0.1 BCH to whoever needs to be compensated. For me, and the other Tech noobs, I think it's best we feel comfortable downloading a wallet that we know is 100% safe.

Thanks!

**Comment by gktown** [comment]
We could write posts regarding open source contributions on utopian.io. They pay for contributions that fit their posting criteria. Its a Steem App that I use for some of my opensource projects.

**Comment by airk42** [comment]
As "Website" - are you referring to ZClassic.org? If such - it links to Eleos wallet. There is also Swing wallet - https://github.com/vaklinov/zclassic-swing-wallet-ui. 
Both are widely used and should not be a problem to setup  

hth

**Comment by WaFeSc** [comment]
I'm working on a new installer. First version creates all folders and makes sure java gets installed (correct version). Next versions will preload part of blockchain.

**Comment by lugeb** [comment]
Do we need design for a new wallet? I've worked on zcash forked wallets (swing wallets for zen, hush).

**Comment by dolb** [comment]
Can you even make a nice - looking interface on swing? I taught this dinosaur tech is used either at college apps just to get some good grade or in 10 - 20 year old apps you see in the industry :) If we want cross platform isn't it better to build an electron app? :) I believe it packs up the whole webkit engine with full CSS3 support :)

**Comment by MCFX2** [comment]
> If we want cross platform isn't it better to build an electron app?
I think electron is a very over-used solution to the UI design problem. It is effectively a new chrome instance, which eats up a lot of memory resources. I don't think java swing is a good solution either, but for a professional wallet something ugly is better than something that won't play nice with old systems. 

If the goal is a resource-friendly but still nice UI, something like [CEGUI](http://cegui.org.uk/), while a bit unorthodox, may suit your needs best.
