### ISSUE TITLE
p2sh error when sweeping private keys into BTCP electrum wallet.

### ISSUE THREAD

**Issue by ericdzen** [BTCPrivate/BitcoinPrivate#122]
### Describe the issue
When I try to sweep my private keys over to the BTCP wallet I am getting a p2sh error.

#### If so, please list the steps to reproduce below:
1. Export private keys from ZCL wallet.
2. Install BTCP electrum wallet
3. Hover the Wallets menu options, go down to private keys, and select the sweep option.
4. Paste all private keys into the text box and press next.
5. p2sh error displays in a modal.
*Note - During the snapshot I was using a 2fa ZCL wallet and switched that wallet to a multi-signature wallet post fork.

### Expected behaviour
Private keys can be swept into the BTCP wallet without running into a p2sh error.

### Actual behaviour + errors
p2sh error occurs when trying to sweeps keys into BTCP electrum wallet.

### The version of Bitcoin Private you were using:
Version P!1.0.0
### Machine specs:
- OS name + version: Windows 10 Home (Version: 1709)
- CPU: 2.4GHz
- RAM: 6.00 GB

**Comment by gmc513** [comment]
Yes I am having the same issue, I had my zcl in the 1.0 wallet as well. I am also getting the p2sh error

**Comment by tinkermade** [comment]
Yes I am having the exact same issue as above.  I initially created a 2FA wallet and discovered that couldn't move ZCL to an exchange address, and was going to have issues.  I used the work-around to create a Multi-sig wallet to access funds.  All of my ZCL addresses begin with T3 and I'm pretty nervous that this is going to impact importing ZCL private keys into BTCP wallet.

**Comment by Ayms** [comment]
You can consider using https://github.com/Ayms/bitcoin-transactions

See also https://bitcointalk.org/index.php?topic=2827163.msg31273044#msg31273044 (simple examples, same applies for p2sh/multisig addresses)

**Comment by ericdzen** [comment]
I wrote another ticket under the Bitcoin Private Electrum wallet project and I was able to resolve this issue there. https://github.com/BTCPrivate/electrum-btcp/issues/13

**Comment by gmc513** [comment]
USE YOUR SEED PHRASE FROM YOUR ZCL WALLET. THAT WORKED FOR ME 

    On Sunday, March 4, 2018 12:54 PM, Eric Dzengeleski <notifications@github.com> wrote:
 

 I wrote another ticket under the Bitcoin Private Electrum wallet project and I was able to resolve this issue there. BTCPrivate/electrum-btcp#13—

**Comment by ragnarrevenge** [comment]
Seed phrase from ZCL? When? During sweep or when creating new wallet?

**Comment by gmc513** [comment]
Creating new wallet
Sent from Yahoo Mail on Android 
 
  On Mon, Mar 5, 2018 at 7:57 AM, ragnarrevenge<notifications@github.com> wrote:   Seed phrase from ZCL? When? During sweep or when creating new wallet?

**Comment by ragnarrevenge** [comment]
Thank you so much. It worked for me, and I moved my btcp to a better wallet
immediately. I have had issues with the electrum wallet, so I don't trust
it.

**Comment by tinkermade** [comment]
Ayms, thanks for sharing to your tool.  I'm still stuck with this multi-sig ZCL wallet that I can't import private keys from into BTCP electrum wallet.  I tried your tx.js script, but there are a few variables that I don't understand, mainly previndex. Please help me to understand:

node tx.js BTCP create `
prevtx=(is this the transaction ID from the previous address (below on the next line)?  Need clarification please)
prevaddr=(the address where ZCL would have been sent from prior to this address (probably chronological?))
prevamount= (I assume it would be the amount of the last transaction [prevaddr=] from the line above)
previndex=(I have no clue.  Can't find on any block explorer. **need major clarification**) 
privkey= (I assume the private key of the address (below on the next line?)
addr=(the address where my ZCL balance was before the snapshot?)
fees= (info found on block explorer or electrum wallet details)
amount= (info found on block explorer or electrum wallet details)

Thank you immensely.

**Comment by Ayms** [comment]
Since this thread is not the place to discuss this, I have opened an issue https://github.com/Ayms/bitcoin-transactions/issues/31#issue-303451989 and will reply there
