### ISSUE TITLE
BTCP Windows Electrum wallet : password issue 

### ISSUE THREAD

**Issue by SmartGuyy** [BTCPrivate/BitcoinPrivate#123]
### Describe the issue

In the BTCP Windows Electrum wallet, at the moment of sweep, i pushed send to transfer my BTCP and i had to write my password, but i did the mistake to  type my password for ZCL Electrum wallet and it succesfully sent it. I'm not sure if it makes a link between them or the password just take whatever you put in for the sweep.
I did not try to send any BTCP to another address to see if it also happens on a normal transaction.

### Can you reliably reproduce the issue?

1. Create new BTCP Windows Electrum wallet and ZCL Electrum wallet (create a password)
2. Sweep your ZCL Private key in BTCP Electrum wallet
3. Send your balance and put your ZCL Electrum wallet password

### Expected behaviour

Transfer succesfully sent.

--> It should refuse the transfer.

**Comment by sedarat** [comment]
Hi where can i download wallet of BTCP ?
