### ISSUE TITLE
sending issue

### ISSUE THREAD

**Issue by QuentinN734** [BTCPrivate/BitcoinPrivate#125]
impossible to send BTCP

steps to reproduce below:
1.I select the address from whom i am sending
2.I select the destination address

Expected behaviour
sending from address to the other
Actual behaviour + errors
Alert window destination address invalid:
The destination address to send BTCP to:
b1.........................
does not appear to be a valid BTCP address. BTCP addresses start with n1, nx or zz!

bitcoin private desktop GUI wallet 1.0.0 ( windows )

- OS name + version: windows 10

**Comment by jmarcott86** [comment]
If you grab the latest 1.0.1 release from https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/releases they've fixed this.

**Comment by QuentinN734** [comment]
thanks, you are correct !

**Comment by d-eco-creative** [comment]
Im still having this issue with version 1.0.4 for mac

**Comment by donshin** [comment]
@d-eco-creative Have you been trying to copy an address from Electrum and paste it into the Full Node Wallet for mac? If so, what you are experiencing is likely this issue: BTCPrivate/bitcoin-private-full-node-wallet#27 .

**Comment by d-eco-creative** [comment]
@donshin Thanks, I copied the electrum wallet address into a text document and then cop/pasted it again into full node wallet and it worked. Thanks for the help :)
