### ISSUE TITLE
electrum wallet btcp mac

### ISSUE THREAD

**Issue by ootisra** [BTCPrivate/BitcoinPrivate#126]
This issue tracker is only for technical issues related to btcpd.

General Bitcoin Private questions and/or support requests and are best directed to the [BTCP Support Website](https://support.btcprivate.org/).

For reporting Zcash-specific security vulnerabilities or for sensitive discussions with their security team, please contact [security@z.cash](mailto:security@z.cash). You can use the [GPG key](https://z.cash/gpg-pubkeys/security.asc) (fingerprint: `AF85 0445 546C 18B7 86F9  2C62 88FB 8B86 D8B5 A68C`) to send an encrypted message. The key and fingerprint are duplicated on our [Public Keys page](https://z.cash/support/pubkeys.html).

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of Bitcoin Private you were using:
Run `btpcd --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.btcprivate/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.btcprivate` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.btcprivate` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by ootisra** [comment]
I have a problem trying to launch the Btcp Electrum wallet for Mac, I get this message: Electrum BTCP quit unexpectedly, and it stop there, my mac os is 10.11.6 el Capitan.

**Comment by ootisra** [comment]
I have a problem trying to launch the Btcp Electrum wallet for Mac, I get this message: Electrum BTCP quit unexpectedly, and it stop there, my mac os is 10.11.6 el Capitan.

**Comment by ootisra** [comment]
I have a problem trying to launch the Btcp Electrum wallet for Mac, I get this message: Electrum BTCP quit unexpectedly, and it stop there, my mac os is 10.11.6 el Capitan.

**Comment by ch4ot1c** [comment]
El Capitan and Yosemite are not yet supported by the Electrum wallet, sorry. Try the full-node wallet.

**Comment by ootisra** [comment]
I have the same problem with the electrum wallet for my El Capitan, but the full node wallet doesnt work either.so I am completely stuck and dont know what to do now.

**Comment by micalways** [comment]
A lot of people such as myself having the same problem... BTCP team are Pro’s an the will come with a solution I hope!
