### ISSUE TITLE
Older Mac Yosemite not able to download electrum BTCP wallet

### ISSUE THREAD

**Issue by micalways** [BTCPrivate/BitcoinPrivate#130]
Dear BTCP Team,

First let me congrat all of yah for your work, I am really happy to be part of this adventure!

I just had a little issue, issue that is generated because I have a older Mac version that I cannot ugrade anymore.
Can you please tell me if you will soon release a Electrum BTCP wallet for MAC Yosemite?

If not can you please tell me how to get my BTCP?

I really thank you for the effort and your goodwill!

Reg, from Belgium

**Comment by ch4ot1c** [comment]
We are working toward it this week. Thanks for the message. https://github.com/BTCPrivate/electrum-btcp/issues would be a more appropriate place for this post; no worries though.
