### ISSUE TITLE
your master branch is not upto date with releases.... 

### ISSUE THREAD

**Issue by scottie** [BTCPrivate/BitcoinPrivate#133]
your master branch is out of date??
your release contains code that is not in your master branch....
1) I clone from from git hub
2) build and sync to latest block
3) run getAddress on daemon
4) get a b1 starting address that is not compatible with wallet GUI....

**Comment by ch4ot1c** [comment]
Full-node wallet 1.0.0 had 'n1' as the prefix still (testnet); b1 is the correct p2pkh addr prefix.
