### ISSUE TITLE
Calculate network difficulty based on legacy powLimit value

### ISSUE THREAD

**Issue by oliverw** [BTCPrivate/BitcoinPrivate#134]
The recently merged PR #131 is problematic in my opinion because this will lead to a situation where the difficulty returned from RPC requests will be 256 times lower than the difficulty calculated by pools from the <code>target</code> property of the blocktemplate.

The powLimit change was already introduced in 11th hour forcing pool developers and operators to scramble to fix the difficulty calculation in the final hours prior to mainnet launch. This change will make things even more confusing.

**Comment by ch4ot1c** [comment]
We've decided to leave this PR in; please update your software to the latest release.
