### ISSUE TITLE
btcpd:  boost::mutex::~mutex(): Assertion `!res' faile

### ISSUE THREAD

**Issue by VERTlG0** [BTCPrivate/BitcoinPrivate#137]
Linux-4.15.4-x64_64 

After downloading the blockchain 7z archive and adding the new dirs to the freshly deleted .btcprivate/ dir(except btcprivate.conf and wallet.dat(made backup)).. re-run ./src/btcpd fails with an error... 

Thank you for running a Bitcoin Private node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using
Bitcoin Private, please see <https://z.cash/support/security/index.html>.

Since starting this node 0 seconds ago:
- You have validated no transactions.

Messages:
- Error:

Init message: Verifying wallet...

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
btcpd: /root/cryptomining/coins/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.
Aborted

**Comment by ch4ot1c** [comment]
I kindly ask you to retry with a more recent version, and to paste `./btcp-cli --version` with the error if you can replicate it.
