### ISSUE TITLE
Can't transfer btcp from imported wallet to standard wallet

### ISSUE THREAD

**Issue by OVGAmining** [BTCPrivate/BitcoinPrivate#143]
I have private key for my zcl address. I created a new wallet on Electrum BTCP. I used the private key to redeem the btcp to the electrum wallet but it say imported wallet instead of standard wallet. I can't send the btcp to any other btcp address. When I try to do a sweep, it only show 6 out of the 35 btcp available to sweep, but in the wallet I have 35 btcp showing.  How do I fix this problem.

**Comment by ch4ot1c** [comment]
Are there multiple private keys? Do you have the seed words (try those first)?

Perhaps you need to 'View->show addresses' in Electrum to see every change address.

Find the remaining 29! ❤️

**Comment by BlueSilver22** [comment]
@OVGAmining please report this issue to the electrum repo: https://github.com/BTCPrivate/electrum-btcp
