### ISSUE TITLE
api issue

### ISSUE THREAD

**Issue by chris334** [BTCPrivate/BitcoinPrivate#148]
This issue tracker is only for technical issues related to btcpd.

General Bitcoin Private questions and/or support requests and are best directed to the [BTCP Support Website](https://support.btcprivate.org/).

For reporting Zcash-specific security vulnerabilities or for sensitive discussions with their security team, please contact [security@z.cash](mailto:security@z.cash). You can use the [GPG key](https://z.cash/gpg-pubkeys/security.asc) (fingerprint: `AF85 0445 546C 18B7 86F9  2C62 88FB 8B86 D8B5 A68C`) to send an encrypted message. The key and fingerprint are duplicated on our [Public Keys page](https://z.cash/support/pubkeys.html).

### Describe the issue
Error: No response from API.
(loadPools)

#### If so, please list the steps to reproduce below:
1.click any link on page
2.
3.

### Expected behaviour
Tell us what should happen 
should come up with the stats no info comes up

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)Error: No response from API.
(loadPools)

### The version of Bitcoin Private you were using:
Run `btpcd --version` to find out

### Machine specs:
- OS name + version: windows 10 64bit
- CPU: amd sempron 145 3ghz
- RAM:4gb
- Disk size: 130gb
- Disk Type (HD/SDD):ssd
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.btcprivate/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.btcprivate` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.btcprivate` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by interbiznw** [comment]
This is a mining pool related issue and it is in regards to using https, that issue was resolved and we now use http://pool.btcprivate.org and the API will load fine.
