### ISSUE TITLE
Add to README at what block height you are taking snapshot of each chain

### ISSUE THREAD

**Issue by sammy007** [BTCPrivate/BitcoinPrivate#15]
It's impossible to follow all the forks really. Need this info in README. Forums are polluted.

**Comment by nimbosa** [comment]
SOON!😺 i think this will come **AFTER** the proper announcement on Twitter and BitcoinTalk?

**Comment by ch4ot1c** [comment]
Snapshot is on February 28! Block TBD. Stay tuned.
