### ISSUE TITLE
Copay btcp wallet

### ISSUE THREAD

**Issue by Jalalrsa** [BTCPrivate/BitcoinPrivate#150]
Is it not possible to make btcp copay wallet for all platforms like android Linux windows osx

**Comment by ch4ot1c** [comment]
Working on it!

**Comment by ch4ot1c** [comment]
BitPay is a constantly moving target. Rest be assured, BIP44 and SLIP44 for BTCP on Copay is already implemented, just no reason to release it until we can finish up a stable release.
