### ISSUE TITLE
Electrum BTCP Wallet -> Not Verified transaction on wallet restore.

### ISSUE THREAD

**Issue by jaafer1214** [BTCPrivate/BitcoinPrivate#152]
### Describe the issue
**System**: Windows 8.1 64 bit
**Wallet**: Electrum BTCP P_1.0.0

#### If so, please list the steps to reproduce below:

1. Download Electrum BTCP wallet to a new PC or delete your current wallet file and start Electrum BTCP wallet again.
2. Restore the BTCP wallet using the seed.
3. Give a new password.
4. Wallet will open and start synchronizing.
5. Once the synchronization is done - balance is shown correctly.

### Expected behaviour
The transaction must show Verified transaction with correct number for confirmations when mouse is hovered on the icon.

### Actual behaviour + errors
The transaction is showing **Not Verified** text. Hovering over the icon shows 0 confirmations. 
BlockExplorer is showing 5500+ confirmations.

### Machine specs:
- OS name + version: Windows 8.1 64 bit
- CPU: Intel Core i5 M520 @2.4Ghz
- RAM: 8 GB
- Disk size: 232 GB
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

**Comment by ch4ot1c** [comment]
You simply need to wait; there should be UI indication for this.

**Comment by interbiznw** [comment]
The blockchain height, and electrum height need to match before correct values will be shown
![alt text](https://i.imgur.com/VvH2LKH.png "screenshot")

**Comment by BlueSilver22** [comment]
@jaafer1214 if you are still having the issue please report it to the electrum repo: https://github.com/BTCPrivate/electrum-btcp
