### ISSUE TITLE
compile error on ubuntu VPS - lib boost not linking 

### ISSUE THREAD

**Issue by BitCoinJedi** [BTCPrivate/BitcoinPrivate#16]
getting error when compiling on my google cloud VPS sees install as unknown linux and doesn't build zcashd fails to link installed lib boost.

Second what is RUST and PROTON?

Thanks

**Comment by samuelngs** [comment]
This is a work-around solution. So open the `btcputil/build.sh` file, remove the `-Werror` flag and build the btcpd again.

**Comment by BitCoinJedi** [comment]
Guys I think I’m losing my
Mind! I can find -Werror coulsnhave siemtjing to donwith the fact I deleted the Vps and started o we with a lower version of Ubuntu I went from 17 to 14.04

**Comment by BitCoinJedi** [comment]
I think someone updated the build.sh file cause I not see -Werror. What am I doing wrong. I really want things going I want to be one of the new BTCprivate mining pools

**Comment by samuelngs** [comment]
https://github.com/BTCPrivate/BitcoinPrivate/blob/master/btcputil/build.sh#L120

**Comment by BitCoinJedi** [comment]
Thanks I fixed libboost depend issue now system is telling me libsnark isn't installed. IM currently trying to fix that. However the install for libsnark isn't very clear. Is there a deb or tar thats compiled I can use?

**Comment by BitCoinJedi** [comment]
Well I deleted all my VPS configs and started a fresh install and got everything to compile without errors but now the btcpd seems to be running but not making any connections

**Comment by Mrwh0** [comment]
in config file addnode=betthis.ddns.net:8033

**Comment by Mrwh0** [comment]
nano /home/yourasomeuserhere/.btcprivate/btcprivate.conf
addnode=betthis.ddns.net:8033
addnode=na1.zclassic.org
addnode=dnsseed.zclassic.org:8033
addnode=dnsseed.rotorproject.org:8033
addnode=betthis.ddns.net:8033
addnode=104.207.149.241:8033
addnode=45.76.4.70:8033
addnode=68.234.31.67:8033
addnode=52.14.116.113:8033
addnode=136.243.50.159:8033
addnode=88.99.199.93:8033
addnode=13.91.45.250:8033
addnode=94.130.11.10:8033
addnode=37.187.167.145:8033
addnode=5.9.111.40:8033
addnode=120.27.230.83:8033
addnode=138.197.199.86:8033
addnode=52.53.125.97:8033
addnode=198.100.147.192:8033
addnode=79.98.144.29:8033
addnode=62.163.150.178:8033
addnode=94.177.229.186:8033
addnode=78.94.32.196:8033
addnode=78.94.32.194:8033
addnode=60.170.218.192:8033
addnode=151.80.96.105:8033
addnode=139.59.230.86:8033
addnode=45.32.233.113:8033
addnode=45.32.234.100:8033
addnode=87.103.195.162:8033
addnode=58.9.134.10:8033
addnode=206.255.161.228:8033
addnode=89.212.102.22:8033
addnode=79.164.95.176:8033
addnode=78.8.88.180:8033
addnode=77.35.255.255:8033
addnode=197.245.248.194:8033
addnode=195.91.186.23:8033
addnode=138.68.48.247:8033
addnode=2.139.88.157:8033
addnode=35.202.93.102:8033

**Comment by jc23424** [comment]
fixed in https://github.com/BTCPrivate/BitcoinPrivate/pull/54
