### ISSUE TITLE
memory pool wtf

### ISSUE THREAD

**Issue by nolteman** [BTCPrivate/BitcoinPrivate#172]
Hostname: electrumx-btcp-us-central-c32b
As of Sat Apr 21 17:46:01 UTC 2018 **# there are 11 transactions in the memory pool**

Help, I'm new in mining , please be simple and specific to help me.

**Comment by nolteman** [comment]
![image](https://user-images.githubusercontent.com/6262110/39088090-bcd8f6fa-4571-11e8-856d-f8f78fc75970.png)
![image](https://user-images.githubusercontent.com/6262110/39088098-dfba6bd6-4571-11e8-93b9-a1cc96346b21.png)

**Comment by nolteman** [comment]
![image](https://user-images.githubusercontent.com/6262110/39088102-feead9b4-4571-11e8-9d7a-8e6e3bbce1c4.png)

**Comment by IceeHot** [comment]
What is the question? Do you need to know what a "memory pool" is?

**Comment by nolteman** [comment]
no, I open the console tab and this appeared






2018-04-21 14:41 GMT-05:00 Eric Domenic-Smith <notifications@github.com>:

**Comment by nolteman** [comment]
http://pool.btcprivate.org/dashboard.html

STUCK, not releasing the coins_?


2018-04-21 14:43 GMT-05:00 Sebastian Nolte <noltealeman@gmail.com>:

**Comment by interbiznw** [comment]
@nolteman  Nobody can delete this page. It is now a piece of history.

**Comment by nolteman** [comment]
Hahahaha Ok thanks                                                                                                                                                                                                                                                                                                                                         Enviado desde mi smartphone BlackBerry 10.                                                                                                                                                                                                                De: J62Enviado: domingo, 22 de abril de 2018 10:50 p.m.Para: BTCPrivate/BitcoinPrivateResponder a: BTCPrivate/BitcoinPrivateCC: nolteman; MentionAsunto: Re: [BTCPrivate/BitcoinPrivate] memory pool wtf (#172)@nolteman  Nobody can delete this page. It is now a piece of history.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BTCPrivate/BitcoinPrivate","title":"BTCPrivate/BitcoinPrivate","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BTCPrivate/BitcoinPrivate"}},"updates":{"snippets":[{"icon":"PERSON","message":"@interbiznw in #172: @nolteman  Nobody can delete this page. It is now a piece of history."}],"action":{"name":"View Issue","url":"https://github.com/BTCPrivate/BitcoinPrivate/issues/172#issuecomment-383446818"}}}
