### ISSUE TITLE
My wallet file corrupted?

### ISSUE THREAD

**Issue by chaddybox026** [BTCPrivate/BitcoinPrivate#173]
I had false txes in my wallet, as in they said they existed but they didn't. I used -zapwallettxes=2 to try to clear the bad txes from the wallet file but all it did was create "wallet.(timestamp).bak" which I cannot open or do anything with.
I'm on windows 8.1 running btcp wallet version 1.0.1

**Comment by ch4ot1c** [comment]
https://github.com/BTCPrivate/walletaid/tree/master

I have successfully used this to recover from a `.bak` ; see if it works for you

**Comment by chaddybox026** [comment]
Ok will do! Thank you!
