### ISSUE TITLE
Problems with a multisign electrum btcp wallet

### ISSUE THREAD

**Issue by Horeas** [BTCPrivate/BitcoinPrivate#174]
Guys i have a problem. I has a 2to2 zcl wallet and i wanted to claim the btcp. I tryied the standard wallet , but no luck, i tried the import priv keys and no luck. Finaly i made a new multisign btcp electrum wallet using the seed i had from the zcl el. wallet and after that i got a public key and in the next box i wrote the zcl wallet public key that i had saved from the time i made that wallet. 

I set a new pass and all synced. Problem is that now i cant move the coins because it needs cosign. in the wallet i see at the first cosigner 1 xpub adress and at the second the zcl electrum wallet one. In zcl its the other way arround. But i cant cosign with zcl cos in zcl wallet i dont get btcp but i get zcl so i got a error.

I thought that i could make a second btcp multisig and i did. First i made a visitor one with the zcl wallet xpub key but could not use it to send coins. 

So i made a new one multisign and selected use a public or private key and at first cosigner i wrote the zcl xpub adress and at the second the btcp xpub adress. It worked and now i have a cosigner but i get fail to cosign. 

What can i do. 

I made a GUI desktop wallet but there i cant import the private keys that i saved before the fork. I get this error.
![2018-04-25_3-56-49](https://user-images.githubusercontent.com/37069708/39233042-ea9a157a-4877-11e8-9c3f-dfb23d571da2.jpg)

Help me out!

**Comment by BlueSilver22** [comment]
Plug your ZCL seed into the BTCP electrum wallet when you make a new wallet.

**Comment by Horeas** [comment]
Its not working man. If i plug in the seed i make a new wallet but the coins dont apear. When i import private k i get 2psh! Its so complicated
