### ISSUE TITLE
Failed Ubuntu install

### ISSUE THREAD

**Issue by FrankK53** [BTCPrivate/BitcoinPrivate#180]
After 2 1-/2 hours of compiling (with a 2 Gb swapfile), my installation failed...
libbitcoin_server_a-torcontrol.o test -f 'torcontrol.cpp' || echo './'torcontrol.cpp
Makefile:3434: recipe for target 'libbitcoin_server_a-torcontrol.o' failed
make[2]:  [libbitcoin_server_a-torcontrol.o] Error 1
make[2]: Leaving directory '/root/BitcoinPrivate/src'
Makefile:5286: recipe for target 'all-recursive' failed
make[1]:  [all-recursive] Error 1
make[1]: Leaving directory '/root/BitcoinPrivate/src'
Makefile:626: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1(edited)
Any help?

**Comment by ch4ot1c** [comment]
Make sure you have the dependencies and follow the instructions.
