### ISSUE TITLE
No hardware device detected MAC OSX

### ISSUE THREAD

**Issue by incognito026** [BTCPrivate/BitcoinPrivate#182]
I try to setup a new BTCP wallet with my ledger nano s but i'm getting this error. Any idea why?
The ledger is unlocked.

![btcpwallet](https://user-images.githubusercontent.com/31889660/39830193-f634a9c8-53c0-11e8-917f-bfbe6554c08a.jpg)

**Comment by ch4ot1c** [comment]
No, sorry; retry in https://github.com/BTCPrivate/electrum-btcp
