### ISSUE TITLE
Testnet sync issue

### ISSUE THREAD

**Issue by mabbas1975** [BTCPrivate/BitcoinPrivate#184]
Hello,
i am running a full node of BTCPrivate but i couldn't sync, is there any nodes i should add in order
to complete syncing, now i stuck at block  310

**Comment by mabbas1975** [comment]
my getinfo output is
{
  "version": 1001251,
  "protocolversion": 180004,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 310,
  "timeoffset": 0,
  "connections": 4,
  "proxy": "",
  "difficulty": 1,
  "testnet": true,
  "keypoololdest": 1526049149,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}

it's stuck at block 310, anybody cal help

**Comment by ch4ot1c** [comment]
I see `testnet: true`; definitely related
