### ISSUE TITLE
autoreconf: automake failed with exit status: 1

### ISSUE THREAD

**Issue by barry-h** [BTCPrivate/BitcoinPrivate#185]
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

hello guys any one can help me with it ?
ubunto 16.0.4

**Comment by ch4ot1c** [comment]
Make sure you have libtool installed, and in your path, and you have the dependencies installed, and are following the instructions.
