### ISSUE TITLE
Minnig Error

### ISSUE THREAD

**Issue by Rockeronhunt** [BTCPrivate/BitcoinPrivate#187]
invalid address length for b1HVuApLpSTtKTT72b9wMXoA67aGhuhSTW2
when i start my node init.js with unomp (creating  UI) my daemon and cli is successfully installed 
i get this address(b1HVuApLpSTtKTT72b9wMXoA67aGhuhSTW2) using this command 
please help me if anyone have the solution

i used this command to get the address --- 

root@ubuntu-s-1vcpu-2gb-nyc1-01:~/BitcoinPrivate# .**/src/btcpd getnewaddress**
Error: There is no RPC client functionality in btcpd. Use the btcp-cli utility instead.

then i tried **./src/btcpd-cli getnewaddress**
please help me 

![untitled](https://user-images.githubusercontent.com/32458821/40579089-c8670d8a-613d-11e8-9c91-eb7e7c493b52.png)

**Comment by michaelotis** [comment]
Try

./src/btcp-cli getnewaddress

**Comment by Rockeronhunt** [comment]
@michaelotis i tried and i get the new address also but when i installed UNOMP for mining 
and run this command **node init.js** I got this error 
![untitled](https://user-images.githubusercontent.com/32458821/40582506-5d78b3f8-6196-11e8-9776-7a940585ca4d.png)

**Comment by Rockeronhunt** [comment]
plz reply @michaelotis

**Comment by michaelotis** [comment]
unomp isn't supported pool software, you need to use z-nomp

**Comment by Rockeronhunt** [comment]
ok sir thanks i start with this if i find any issue i ll let u know

**Comment by Rockeronhunt** [comment]
thanks @michaelotis for helping m i solved this issue one more question i have 
what is this three address & how i can get all this address

    "address": "",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

**Comment by Rockeronhunt** [comment]
![image](https://user-images.githubusercontent.com/32458821/42763148-d29bd032-892f-11e8-810d-2b2011d878a2.png)
I try using z-nomp with bitcoinprivate & everything is successfully working but when i mined my coin i am not getting any block.
