### ISSUE TITLE
Testnet please!

### ISSUE THREAD

**Issue by mabbas1975** [BTCPrivate/BitcoinPrivate#188]
Hello,
please help the testnet is sucked at block 310, we reported this issue before without any reply should we
a specific version now we got this error

 InvalidChainFound:  current best=06cafcbaf45ad0350ef8c1386fe687dc75e923c06dea2f17747d181e4b00d45b  height=310  log2_work=13.280771  date=2018-02-22 14:41:35

please help we are working in a project and we are waiting the testnet eagerly

**Comment by ch4ot1c** [comment]
@michaelotis @donshin

**Comment by ch4ot1c** [comment]
Use `-regtest` for this version if need be; we're configuring a testnet at BTCPrivate/BTCP-Rebase.
