### ISSUE TITLE
BTCP Nodes List

### ISSUE THREAD

**Issue by milaas** [BTCPrivate/BitcoinPrivate#189]
is there a bitcoin private node list for the btcprivate.conf
a mean more than this:
addnode=dnsseed.btcprivate.org
addnode=dnsseed.btcprivate.co
take so long to sync...

           Block height | 278153
            Connections | 8
  Network solution rate | 2 Sol/s

**Comment by ch4ot1c** [comment]
The dnsseed should serve all peers just fine; For more than 8 cxns, be sure to open the p2p port 7933.

**Comment by interbiznw** [comment]
Yeah @milaas  the dnsseed provides the list of nodes, you can run a DNS address query on dnsseed.btcprivate.co and see that it returns a list plenty big enough to get nodes listed. If you do not open the p2p port 7933 you will never get more than 8 connections regardless.
