### ISSUE TITLE
Hardfork - before Feb 16 - test gettxoutsetinfo

### ISSUE THREAD

**Issue by mattpass** [BTCPrivate/BitcoinPrivate#205]
Info advised from someone on a rather crucial item, noting here for someone to deal with...

**Test to be sure that gettxoutsetinfo does not show the burned coins.**

**It was not tested prior to the last hard fork because it was anticipated we would have time to implement a fix after the hard fork. You should be certain this will work properly. This is priority #1 as it should be working before Feb 16.**

**Comment by Daz2** [comment]
yeah, not sure how to get red letters on git.. seems like a good project.

**Comment by TrueDetective** [comment]
Team is always looking for adding new developers. If interested.

**Comment by interbiznw** [comment]
Closed as no longer relevant
