### ISSUE TITLE
Transaction sended but not shown on exlorer \ mined

### ISSUE THREAD

**Issue by jRazer** [BTCPrivate/BitcoinPrivate#207]
Transaction sended but not shown on exlorer \ mined
debug log without error

TXID: aedefa95f53fafc1c5d8de5a1c74bf4af1819da3373892bec3e40cf3375f536b
Bitcoin Private Daemon version v1.0.13-g6c8ed84c5

**Comment by jRazer** [comment]
Thanks, I will try now

**Comment by interbiznw** [comment]
Transaction was probably in the mempool on that node only and not actually sent. Did upgrading to new version resolve this issue @jRazer ?

**Comment by jRazer** [comment]
Upgrade and reindex blockchain
