### ISSUE TITLE
Any bounties for the 3rd party clients & libraries & services?

### ISSUE THREAD

**Issue by akx20000a** [BTCPrivate/BitcoinPrivate#21]
I can work for
+ Core-based fork client
+ compatible with BTC Core
+ Gitian build environment (Already worked for the BTCGPU)
+ Java libraries for the mobile wallet
+ Explorer service
+ Mining Pool service
+ Mining client tuning
+ Some seed nodes
+ Dns-seeds
+ Korean translation & advertisement & contract

You can contract me with akx20000@protonmail.com or slack anytime

**Comment by heyrhett** [comment]
Yes!  We need electrum wallet clones!
https://github.com/BTCPrivate/BitcoinPrivate/issues/24

**Comment by akx20000a** [comment]
@heyrhett Got it

**Comment by MopTcodE** [comment]
Still need Japanese translation in certain area?

**Comment by kitaboleh** [comment]
안녕하세요 비트코인토크 계정 판매하려고 이메일이랑 dm도 보냈습니다. 제 닉네임은 nivernova 에요
