### ISSUE TITLE
Change the diff algorithm

### ISSUE THREAD

**Issue by akx20000a** [BTCPrivate/BitcoinPrivate#22]
Changing the diff algorithm will be more preferable for the fork I think.
Also it will be the good chance if we make the block time much faster.

**Comment by leto** [comment]
There has been a lot of research on this, I highly suggest looking at all the data the Hush community has compiled and talking to our resident difficulty algo expert: https://github.com/MyHush/hush/issues/24 @zawy12

**Comment by leto** [comment]
TLDR: EMA http://zawy1.blogspot.com/2017/11/best-difficulty-algorithms.html

**Comment by zawy12** [comment]
Thanks duke for the reference.  Here's where I'm keeping the newest info:
https://github.com/zawy12/difficulty-algorithms/issues/1

**Comment by zawy12** [comment]
We've developed a new algorithm that's the best of the best and allows integer math on the target.

https://github.com/zawy12/difficulty-algorithms/issues/17

**Comment by heyrhett** [comment]
Solved by latest branch https://github.com/BTCPrivate/BitcoinPrivate/tree/cb-inputs
