### ISSUE TITLE
where are my coins? 

### ISSUE THREAD

**Issue by madtomic** [BTCPrivate/BitcoinPrivate#225]
I just got my wallet sync and my coins are gone? 

From my understanding, you guys were targeting shielded coins. Why are you burning my coins that never moved since I claimed them from snapshot. You can see that all coins were legit from 1:1 exchanged.

My address, b1BFy2UAo4RNVo5PD8nH4XMihqpZUijaTor

![image](https://user-images.githubusercontent.com/6004542/54731217-64699f80-4b63-11e9-9c38-570b244bbcbe.png)

**Comment by interbiznw** [comment]
According to the explorer and that scerenshot the coins are in that wallet address. Likely your wallet wasn't or isn't synced fully if it's still not showing those coins. As of right now, the explorer is still showing that address with a balance.

The shielded coin burn has nothing to do with transparent coins, your referring two different things.

The regular coin burn that happened on unclaimed coins also would not have burned your coins if you actually followed the claim process after the fork.

If this is still an issue feel free to reopen, But I am guessing a wallet sync resolved the issue.
