### ISSUE TITLE
Build issue while Fetching libsnark...

### ISSUE THREAD

**Issue by ajabnoor** [BTCPrivate/BitcoinPrivate#226]
I am trying to install the latest wallet on Ubuntu 18.04.2 LTS on a VM but the install stops at the following error

2019-03-29 05:11:39 ERROR 403: Forbidden.
wget: unable to resolve host address ‘github.com’
funcs.mk:242: recipe for target '/home/xxxx/BTCP/BitcoinPrivate/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash' failed
make: *** [/home/xxxx/BTCP/BitcoinPrivate/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash] Error 4
make: Leaving directory '/home/xxxx/BTCP/BitcoinPrivate/depends'

**Comment by ajabnoor** [comment]
I just solved it by installing latest ubuntu server version and works fine

**Comment by interbiznw** [comment]
Thanks for posting the resolution, for documentation purposes for others that may run into this.

But seems like a networking or DNS issue was the root cause as it couldn't resolve github.com OR possibly the way you cloned.
