### ISSUE TITLE
Cannot fetch zcash parameters

### ISSUE THREAD

**Issue by AlexeyRudoy** [BTCPrivate/BitcoinPrivate#228]
### Describe the issue
Cannot fetch the network parameters using the provided scripts - looks like the files are gone from Google.

#### If so, please list the steps to reproduce below:
1. ./zcash-fetch-params OR ./btcputil/fetch-params.sh

### Actual behaviour + errors

*root@f80fc55ab703:/tmp/btcp/depends/x86_64-unknown-linux-gnu/bin# ./zcash-fetch-params
Bitcoin Private - fetch-params.sh*

*This script will fetch the Bitcoin Private (and Zcash) zkSNARK parameters, and verify
their integrity with sha256sum. These parameters are identical to those for
both Zclassic and Zcash.*

*If they already exist locally, it will exit now and do nothing else.
Retrieving: https://storage.googleapis.com/btcp-sprout-key/sprout-proving.key
./zcash-fetch-params: line 27: sw_vers: command not found
--2019-07-03 17:31:43--  https://storage.googleapis.com/btcp-sprout-key/sprout-proving.key
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.215.112, 2a00:1450:401b:807::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.215.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-03 17:31:43 ERROR 404: Not Found.*

### The version of Bitcoin Private you were using:
*Bitcoin Private Daemon version v1.0.13-53e4647*

### Machine specs:
- OS name + version: Debian Stretch (Docker)
- CPU: i5 
- RAM: 24Gi
- Disk size: 2Tb
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): Linux f80fc55ab703 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by bigdaveakers** [comment]
As a temporary measure the parameters can be downloaded from here

https://drive.google.com/file/d/1absJU3zcdawg2YZ77WP5hkfx_5WqifbZ/view

The BTCP infrastructure is undergoing rationalisation and as such some services and files are being rehosted to reduce costs. This was an oversight during transition and will be remedied at the next code release.

**Comment by aguilaair** [comment]
Updated link: https://drive.google.com/open?id=1fAfBX_x41rzzSwlMkhKytLJbSNi94_PP

**Comment by interbiznw** [comment]
Solved in #235
