### ISSUE TITLE
Electrum Wallet Clone for Zclassic / Bitcoin Private

### ISSUE THREAD

**Issue by heyrhett** [BTCPrivate/BitcoinPrivate#24]
Zclassic and Bitcoin Private need electrum wallet clones to make sure people have an easy way to access and transact their coins through the fork.

EDIT (BlueSilver): email bitcoinprivateofficial@gmail.com if you would like to join the development team. We have one person working on this but we need more to get it out faster.

**Comment by akx20000a** [comment]
Well I've heard that there is no electrum wallet clones for the equihash coins or ZCash-based coins.
However, I am working on the electrum fork for the BTG. I can receive this one

**Comment by BlueSilver22** [comment]
Hush is a fork of ZCash and has Electrum wallet close to release, so clearly it is possible: https://github.com/matthewjamesr/hush-ng

**Comment by heyrhett** [comment]
@akx20000a any time estimate?  Should we assign you?

**Comment by akx20000a** [comment]
@heyrhett About 1~2 weeks will be taken and yes assign as a contributor will be good :D

**Comment by heyrhett** [comment]
Hi, @akx20000a we do have someone working on this as well, but it's unclear what their time frame is.  Is there a way to rush the zclassic version as fast as possible, and what bounty would you like for that?

**Comment by BlueSilver22** [comment]
@akx20000a I think the best possible solution is to bring you into our discord and have you work with the current developer to get it done as fast as possible. Is that something that you would be interested in?

**Comment by akx20000a** [comment]
@heyrhett @BlueSilver22 That would be nice.

**Comment by BlueSilver22** [comment]
@akx20000a https://discord.gg/Ejvvgd

Only good for one use so make sure to snag it quick

**Comment by akx20000a** [comment]
@heyrhett And since I need to analyze the code of zcash(especially zk-snarks), it will take some time.
I would like to receive 1.2 BTC for the ZClassic one.

**Comment by akx20000a** [comment]
@BlueSilver22 Thanks

**Comment by leto** [comment]
@akx20000a sorry to break the news but I have already added Equihash-based coins to ElectrumX, like Hush: https://github.com/kyuupichan/electrumx/commit/02438e488d32dc3cb479d747248e7ea3dd83840d

@heyrhett you want me to add BTCP to ElectrumX? Make a bounty offer, more than 1.2BTC please.

Also, you need to know if you are asking for the entire backend and fronted, or just backend for this bounty. There is a lot of work, much more than 1.2BTC to do it all.

It sounds like y'all are very new to Electrum-world, I can guide you.

**Comment by BlueSilver22** [comment]
@leto we have two Devs working on this right now. We would love to have you come join the discord and work with them on both sides. We can discuss the reward amount in the discord. Link is only good for one use so get on it quick: https://discord.gg/5CrFWv

**Comment by BlueSilver22** [comment]
@leto someone seems to have claimed the last one, here is another in case it was not you: https://discord.gg/S7Trer

**Comment by ch4ot1c** [comment]
@leto I believe we've already got that commit completed:
https://github.com/kyuupichan/electrumx/commit/4dd226f9c090d968b80360d607368f5213ccaa56

Hands-on-deck and experienced minds are always welcome! Please reach out :)

**Comment by leto** [comment]
@ch4ot1c looks like y'all have this, I am going to step back from this bounty. Don't have too much fun without me!

**Comment by kryptocoin99** [comment]
Are you guys familiar with this critical Electrum vulnerability.
"A vulnerability was found in the Electrum wallet software which potentially allows random websites to steal your wallet via JavaScript. The bug presumably also affects altcoin derivatives of Electrum such as Electron Cash."

Details here: bitcointalk.org/index.php?topic=2702103.0

**Comment by akx20000a** [comment]
@leto  I think we will need a client like https://github.com/fyookball/electrum. If you have one for hush let me know please.

**Comment by michaelotis** [comment]
I've been working on a little GUI revamp

![image](https://user-images.githubusercontent.com/34221002/34864565-7a861772-f73a-11e7-9efc-3e76b9a3895d.png)
![image](https://user-images.githubusercontent.com/34221002/34864742-5e245b7e-f73b-11e7-834d-b5a8a9db4c82.png)

**Comment by mattpass** [comment]
Re @kryptocoin99 comment here https://github.com/BTCPrivate/BitcoinPrivate/issues/24#issuecomment-355884571 I'd say I'm concerned about this bug also and sounds like 3.0.5 or above is needed, see here https://github.com/spesmilo/electrum-docs/blob/master/cve.rst

Is the latest version being used here and the bug not present?

**Comment by thecryptoguy** [comment]
@michaelotis I was thinking to develop UX with electron too as all the other clients are not easier to maintain. Let me know if you need any help.

**Comment by alfredolopez80** [comment]
kn@heyrhett i can help you in some issue, i'm not sure for all solution, but i nrw but i'm a programmer and i want to help for hours and Bounty so if you need some guy for Banked o Front end, only send me i email alfredolopez80@gmail.com

**Comment by MopTcodE** [comment]
I assume this has been taken care of correct? In case need more hands, let me know.

**Comment by Ayms** [comment]
FYI people can use this tool to transact their coins: https://github.com/Ayms/bitcoin-transactions

I just added Bitcoin Private https://github.com/Ayms/bitcoin-transactions/issues/15

**Comment by ch4ot1c** [comment]
Progress is underway 🐎  ! T->T are sendable and visible, and Z->T txns are visible.
Please get the latest release: https://github.com/BTCP-community/electrum-zcl

**Comment by ddelapaz** [comment]
Any way we can get Bitcoin Private on Coinomi? I'm not sure what the process is there but sounds like they should be able to add it quickly since they currently support ZEN and ZEC.

**Comment by BlueSilver22** [comment]
@ddelapaz we announced Coinomi support a week ago. They should have ZCL this week and will have BTCP directly after the fork: https://twitter.com/bitcoinprivate/status/959566948790161408

**Comment by amirn44** [comment]
guys i use electrum wallet and its not connected!! plz help me

**Comment by manuel734** [comment]
@amirn44 what issue are you having with the wallet?

**Comment by ch4ot1c** [comment]
The process is underway and we have enough developers to see it through. Please join us on Discord - https://discord.gg/bBt9d3x - if you want to get involved with this project or would like an assignment. Thank you!
