### ISSUE TITLE
Compile error on Linux Mint 18 Sarah

### ISSUE THREAD

**Issue by MFGNetworks** [BTCPrivate/BitcoinPrivate#25]
zclassic, zcash compile fine but not BitcoinPrivate
I did remove the --Werror flag from btcputil/build.sh to try to fix this
Help needed
I have added the following lines

THX

In file included from script/interpreter.cpp:6:0:
script/interpreter.h:92:43: warning: left shift count >= width of type [-Wshift-count-overflow]
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),
                                           ^
script/interpreter.cpp: In function ‘bool CheckSignatureEncoding(const valtype&, unsigned int, ScriptError*)’:
script/interpreter.cpp:210:38: error: ‘SCRIPT_ERR_ILLEGAL_BTCP_FORKID’ was not declared in this scope
             return set_error(serror, SCRIPT_ERR_ILLEGAL_BTCP_FORKID);
                                      ^
script/interpreter.cpp:214:38: error: ‘SCRIPT_ERR_ILLEGAL_BTCP_FORKID’ was not declared in this scope
             return set_error(serror, SCRIPT_ERR_ILLEGAL_BTCP_FORKID);
                                      ^
Makefile:2886: recipe for target 'script/libbitcoin_common_a-interpreter.o' failed
make[2]: *** [script/libbitcoin_common_a-interpreter.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -m64 -DHAVE_CONFIG_H -I.   -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/  -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT lib/libunivalue_la-univalue_read.lo -MD -MP -MF lib/.deps/libunivalue_la-univalue_read.Tpo -c -o lib/libunivalue_la-univalue_read.lo `test -f 'lib/univalue_read.cpp' || echo './'`lib/univalue_read.cpp
libtool: compile:  g++ -m64 -DHAVE_CONFIG_H -I. -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/ -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT lib/libunivalue_la-univalue_read.lo -MD -MP -MF lib/.deps/libunivalue_la-univalue_read.Tpo -c lib/univalue_read.cpp  -fPIC -DPIC -o lib/libunivalue_la-univalue_read.o
mv -f .deps/libbitcoin_common_a-protocol.Tpo .deps/libbitcoin_common_a-protocol.Po
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -m64 -DHAVE_CONFIG_H -I.   -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/  -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT lib/libunivalue_la-univalue_write.lo -MD -MP -MF lib/.deps/libunivalue_la-univalue_write.Tpo -c -o lib/libunivalue_la-univalue_write.lo `test -f 'lib/univalue_write.cpp' || echo './'`lib/univalue_write.cpp
mv -f script/.deps/libbitcoin_common_a-script.Tpo script/.deps/libbitcoin_common_a-script.Po
g++ -m64 -DHAVE_CONFIG_H -I.   -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/  -I./include -DJSON_TEST_SRC=\"./test\" -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT test/test_unitester-unitester.o -MD -MP -MF test/.deps/test_unitester-unitester.Tpo -c -o test/test_unitester-unitester.o `test -f 'test/unitester.cpp' || echo './'`test/unitester.cpp
libtool: compile:  g++ -m64 -DHAVE_CONFIG_H -I. -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/ -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT lib/libunivalue_la-univalue_write.lo -MD -MP -MF lib/.deps/libunivalue_la-univalue_write.Tpo -c lib/univalue_write.cpp  -fPIC -DPIC -o lib/libunivalue_la-univalue_write.o
mv -f lib/.deps/libunivalue_la-univalue_write.Tpo lib/.deps/libunivalue_la-univalue_write.Plo
g++ -m64 -DHAVE_CONFIG_H -I.   -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/  -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT test/test_no_nul-no_nul.o -MD -MP -MF test/.deps/test_no_nul-no_nul.Tpo -c -o test/test_no_nul-no_nul.o `test -f 'test/no_nul.cpp' || echo './'`test/no_nul.cpp
mv -f test/.deps/test_unitester-unitester.Tpo test/.deps/test_unitester-unitester.Po
g++ -m64 -DHAVE_CONFIG_H -I.   -I/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/  -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -MT test/test_test_json-test_json.o -MD -MP -MF test/.deps/test_test_json-test_json.Tpo -c -o test/test_test_json-test_json.o `test -f 'test/test_json.cpp' || echo './'`test/test_json.cpp
mv -f lib/.deps/libunivalue_la-univalue.Tpo lib/.deps/libunivalue_la-univalue.Plo
mv -f test/.deps/test_no_nul-no_nul.Tpo test/.deps/test_no_nul-no_nul.Po
mv -f lib/.deps/libunivalue_la-univalue_read.Tpo lib/.deps/libunivalue_la-univalue_read.Plo
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -m64 -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -version-info 100:3:100 -no-undefined -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib  -o libunivalue.la -rpath /home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/lib lib/libunivalue_la-univalue.lo lib/libunivalue_la-univalue_read.lo lib/libunivalue_la-univalue_write.lo  
libtool: link: ar cru .libs/libunivalue.a  lib/libunivalue_la-univalue.o lib/libunivalue_la-univalue_read.o lib/libunivalue_la-univalue_write.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libunivalue.a
libtool: link: ( cd ".libs" && rm -f "libunivalue.la" && ln -s "../libunivalue.la" "libunivalue.la" )
mv -f test/.deps/test_test_json-test_json.Tpo test/.deps/test_test_json-test_json.Po
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -m64 -I./include -DJSON_TEST_SRC=\"./test\" -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -static  -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib  -o test/unitester test/test_unitester-unitester.o libunivalue.la 
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -m64 -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -static  -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib  -o test/no_nul test/test_no_nul-no_nul.o libunivalue.la 
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -m64 -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -static  -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib  -o test/test_json test/test_test_json-test_json.o libunivalue.la 
mv -f .deps/libbitcoin_common_a-netbase.Tpo .deps/libbitcoin_common_a-netbase.Po
libtool: link: g++ -m64 -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -o test/test_json test/test_test_json-test_json.o  -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib ./.libs/libunivalue.a
libtool: link: g++ -m64 -I./include -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -o test/no_nul test/test_no_nul-no_nul.o  -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib ./.libs/libunivalue.a
libtool: link: g++ -m64 -I./include -DJSON_TEST_SRC=\"./test\" -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -g -o test/unitester test/test_unitester-unitester.o  -L/home/jop/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../lib ./.libs/libunivalue.a
make[4]: Leaving directory '/home/jop/BitcoinPrivate/src/univalue'
make[3]: Leaving directory '/home/jop/BitcoinPrivate/src/univalue'
mv -f .deps/libbitcoin_common_a-scheduler.Tpo .deps/libbitcoin_common_a-scheduler.Po
In file included from ./script/sign.h:9:0,
                 from script/sign.cpp:6:
./script/interpreter.h:92:43: warning: left shift count >= width of type [-Wshift-count-overflow]
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),
                                           ^
mv -f script/.deps/libbitcoin_common_a-sign.Tpo script/.deps/libbitcoin_common_a-sign.Po
In file included from ./script/standard.h:9:0,
                 from script/standard.cpp:6:
./script/interpreter.h:92:43: warning: left shift count >= width of type [-Wshift-count-overflow]
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),
                                           ^
mv -f script/.deps/libbitcoin_common_a-standard.Tpo script/.deps/libbitcoin_common_a-standard.Po
make[2]: Leaving directory '/home/jop/BitcoinPrivate/src'
Makefile:5228: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/jop/BitcoinPrivate/src'
Makefile:626: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by deltamike-x** [comment]
Same issue observed on Ubuntu Server 16.04.3

`mv -f .deps/btcpd-bitcoind.Tpo .deps/btcpd-bitcoind.Po
make[2]: Leaving directory '/home/deltamike/BitcoinPrivate/src'
Makefile:5228: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/deltamike/BitcoinPrivate/src'
Makefile:626: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by airk42** [comment]
From the second comment - I don't see how it is the same as first
Log in the first comment was result in the some merge errors and was fixed with PR #29 

@deltamike-x try with that new code if still failing, open new issue with full log
