### ISSUE TITLE
compiling error on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by robbiewu008** [BTCPrivate/BitcoinPrivate#26]
Making all in src
make[1]: Entering directory '/home/robbie/Work/BitcoinPrivate/src'
make[2]: Entering directory '/home/robbie/Work/BitcoinPrivate/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile /home/robbie/Work/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I./obj -I./secp256k1/include -DBUILD_BITCOIN_INTERNAL -I/home/robbie/Work/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/robbie/Work/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT script/libzcashconsensus_la-zcashconsensus.lo -MD -MP -MF script/.deps/libzcashconsensus_la-zcashconsensus.Tpo -c -o script/libzcashconsensus_la-zcashconsensus.lo `test -f 'script/zcashconsensus.cpp' || echo './'`script/zcashconsensus.cpp
libtool: compile:  /home/robbie/Work/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I./obj -I./secp256k1/include -DBUILD_BITCOIN_INTERNAL -I/home/robbie/Work/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/robbie/Work/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/ -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT script/libzcashconsensus_la-zcashconsensus.lo -MD -MP -MF script/.deps/libzcashconsensus_la-zcashconsensus.Tpo -c script/zcashconsensus.cpp  -fPIC -DPIC -o script/.libs/libzcashconsensus_la-zcashconsensus.o
In file included from script/zcashconsensus.cpp:10:0:
./script/interpreter.h:92:43: error: left shift count >= width of type [-Werror=shift-count-overflow]
     SCRIPT_ENABLE_SIGHASH_FORKID = (1U << 42),
                                           ^
cc1plus: all warnings being treated as errors
Makefile:4055: recipe for target 'script/libzcashconsensus_la-zcashconsensus.lo' failed
make[2]: *** [script/libzcashconsensus_la-zcashconsensus.lo] Error 1
make[2]: Leaving directory '/home/robbie/Work/BitcoinPrivate/src'
Makefile:5228: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/robbie/Work/BitcoinPrivate/src'
Makefile:626: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by dolb** [comment]
Ill test it out and try to reproduce if possible.

**Comment by airk42** [comment]
Fixed by PR #29
