### ISSUE TITLE
P2P and RPC ports

### ISSUE THREAD

**Issue by Skyryn** [BTCPrivate/BitcoinPrivate#34]
I see that BTCPrivate and ZCL are using the same P2P port and RPC port is this going to stay that way?.. 
if so we could not run ZCL and BTCP  nodes on the same server

I also see it is syncing with the ZCL chain
same blocks as ZCL
is there going to be a new chain?
We are syncing the chain now using the BTCP node and may be waiting our time
in prep for mining pool and block explorer

**Comment by Alexintosh** [comment]
It's my understanding that Zclassic chain will be converted to BTCPrivate once it's out. Am I right?

**Comment by jc23424** [comment]
Thanks - yes - I just submitted a change to begin doing that. Please see
https://github.com/BTCPrivate/BitcoinPrivate/pull/40

**Comment by ch4ot1c** [comment]
P2P: 7933, RPC: 7932

**Comment by VERTlG0** [comment]
Is there a TCP/UDP port option such as how ETHASH runs nodes together.. We specify one as 30303 and another as 30305.
