### ISSUE TITLE
poor german translation quality of btcprivate.org

### ISSUE THREAD

**Issue by Skillcommand** [BTCPrivate/BitcoinPrivate#35]
#### Hello BTCP contributors,
I don't know where I should ask for this problem because there's no public visible contribution system concerning your website translations. I've tweeted (@)bitcoinprivate already and created a reddit post about that problem [(Website) poor german translation](https://redd.it/7pj4s7)

I'm happy about the fact that your website is getting more languages over time but especially the German translation is full of mistakes which can affect the reader's opinion negatively or at least presents BTCP in an unprofessional way.

### The mistakes are characterized by
- wrong sentence structures
- serval synonyms seperated by a slash in a scentence (you never do that in any language)
- spelling mistakes
- word mistakes
- capitalization mistakes
- wrong personal pronouns

As a native German speaker and a supporter of the idea behind BTCP I would like to help you solving that issue.
You just need to tell me how I can suggest you a better translation for each of your website's sections.

Best regards

**Comment by FranzouilleWazaah** [comment]
Hello Skillcommand, 

I think you can directly edit this google doc : https://docs.google.com/document/d/1vUYyGxNQZS7njBbo3BsGKyW7DjWspayihJs9ytfgkk4/edit

You can also discuss about it with other german contributors on the discord for translations : https://discord.gg/kq3JcB

Kind regards,
FranzouilleWazaah

**Comment by cryptobat** [comment]
Here's my Romanian Translation: https://docs.google.com/document/d/1m-6-eAv38C3sno8-uzYpGxZGJ9xSXe1JsfjkrlJPF58/edit?usp=sharing
