### ISSUE TITLE
21 Million total supply

### ISSUE THREAD

**Issue by justinjja** [BTCPrivate/BitcoinPrivate#38]
I have seen it suggested that the total supply is going to be 21 Million.

Are the halvings being accelerated or is the block reward being reduced?
Or is the total supply actually going to be ~37.8 Million?

https://pbs.twimg.com/media/DTRRZhdWkAI0vNX.jpg

**Comment by gktown** [comment]
Total supply = 21M - Why would it be 37.8M?

**Comment by justinjja** [comment]
My understanding is the block reward is halved every x blocks, and after 64 halvings the block reward is set to 0.
Nothing specifically limits the total supply to 21M that is just how it works out.

So when 16.8M bitcoins are inserted over only a small number of blocks, the block reward will remain unchanged, and the total supply will reach 21M mined coins + 16.8M inserted BTC coins = 37.8M total

**Comment by dolb** [comment]
Youll have 21M coins (BTC snapshot base - SEGWIT - something else that is problematic) + snapshot ZCL  balances which is currently roughly over 3M - that gives an amount below 21M - then the block reward will be adjusted.

**Comment by justinjja** [comment]
Has the block reward adjustment already been coded?

**Comment by MopTcodE** [comment]
May be good to double check on this now than later.

**Comment by dolb** [comment]
In Bitcoin it is coded for 210k blocks - here it is probably not done yet, as I haven't seen it on the 'DONE' checklist yet ;)

**Comment by chompomonim** [comment]
> BTC snapshot base - SEGWIT - something else that is problematic

So, you will not have SEGWIT support? And BTC holders who use SEGWIT addresses will not get coins?

Also what is "something else that is problematic"?

+1 for adding reward adjustment even before fork happens.

**Comment by ch4ot1c** [comment]
https://btcprivate.org/whitepaper.pdf section 7
