### ISSUE TITLE
Get Unspent Output Set For Bitcoin Private Fork

### ISSUE THREAD

**Issue by heyrhett** [BTCPrivate/BitcoinPrivate#4]
https://blockchair.com/bitcoin-cash/outputs?q=is_spent(0)

Here is one way to do it for Bitcoin Cash... 65M results.

https://github.com/Blockchair/Blockchair.Support/issues/53

<img width="876" alt="screen shot 2017-12-25 at 6 24 22 am" src="https://user-images.githubusercontent.com/2388024/34339636-517f7dfc-e93c-11e7-8af4-7530679554f0.png">

**Comment by coinsoncoins** [comment]
for BTC-fork minus segwit, how about 
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(pubkeyhash)
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(pubkey)
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(scripthash)
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(multisig)
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(nulldata)
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(nonstandard)

and NOT
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(witness_v0_keyhash)
https://blockchair.com/bitcoin/outputs?q=is_spent(0),type(witness_v0_scripthash)

this leads to about 68M results

**Comment by heyrhett** [comment]
We can't query more than a million at a time easily for free. Any way you can break those up, maybe by date range so we know we can always download all the results easily for a given block height snapshot?

**Comment by coinsoncoins** [comment]
looking into this

**Comment by coinsoncoins** [comment]
blockchair will only let you filter 2 parameters at once, so we can do multiple requests which are less than 1 million cells each

https://api.blockchair.com/bitcoin/outputs?q=is_spent(0),transaction_id(0..500000)&fields=transaction_id,index,time,recipient,type,value&export=csv
https://api.blockchair.com/bitcoin/outputs?q=is_spent(0),transaction_id(500000..1000000)&fields=transaction_id,index,time,recipient,type,value&export=csv
... etc ...

collect all the CSV files and then filter by "types" that are only in [pubkey, pubkeyhash, scripthash, multisig, nulldata, nonstandard]

**Comment by ulloa** [comment]
I am writing an R script that will download these all and then filter the data (for not type witness) using R into one large CSV. You will be able to run it using a shell script. Is that what we want?

**Comment by heyrhett** [comment]
I think that would help to make sure we can reliably download them

**Comment by ulloa** [comment]
I am actively working on this. Just debugging and making sure it is extendable now.

**Comment by ulloa** [comment]
JC will do the task by using a full node. 

Blockchair may not be the most reliable solution. Limits on their API are very limiting. This was my last progress on the task using Blockchair: https://github.com/ulloa/blockchairScrape/blob/master/getData.sh

**Comment by jc23424** [comment]
please see https://github.com/jc23424/utxo_dump

**Comment by standy66** [comment]
@heyrhett Hello, is this issue still relevant? I can do the same work as @jc23424 but using Blockchair API and Python. Redundancy may be good for double checking the utxo set before the fork.

**Comment by Har01d** [comment]
Hello, Blockchair lead dev here.

If you need help with getting the UTXO set at a specific block height, please contact us at <info@blockchair.com>, I guess we’ll be able to help.

**Comment by ch4ot1c** [comment]
@Har01d, @standy66, thank you for the offer! <3

We are all set though:
https://github.com/jc23424/utxo_dump

Please review this; we consider it nearly final
