### ISSUE TITLE
Bitcoin Private Logo Proposal

### ISSUE THREAD

**Issue by nimbosa** [BTCPrivate/BitcoinPrivate#42]
### Logo Weight, Color, Balance and Bitcoin Angle Proposal
i noticed that the logo we have now on the website is a little bit off-center, and the color seems too dark or too dry? BLUE signifies security, stability and reliability, it evokes the feeling of trust. so i propose this, recentred and recoloured:

![Bitcoin Private Trio](https://i.imgur.com/otptI2R.png "Bitcoin Private Trio")

if you notice, the current working logo has too much weight on the Fourth Quadrant (Lower Right) and spaces are too wide on Quadrants 1, 2 & 3, it looks like falling off the circle.. **SO** i propose centering the inner border of the second bar of the modified Bitcoin symbol to be aligned with the diameter of the circle, and re-tilted 14.67 degrees counter-clockwise; THIS gives the logo a balanced weight with the symbol within it

&nbsp;

This is the logo using HEX:#**004090** /Pantone Matching System [293 C](http://rgb.to/hex/004090):

![#BitcoinPrivate in nimbosa BLUE](https://i.imgur.com/YFmbbHP.png "#BitcoinPrivate in nimbosa BLUE")

Colour Values as a [JSON file](http://rgb.to/save/json/color/004090):

```
{
  "hex":"#004090",
  "websafe":"#003399",
  "rgb":{
    "r":0,
    "g":64,
    "b":144
  },
  "hsl":{
    "h":213,
    "s":100,
    "l":28
  },
  "hsb":{
    "h":213,
    "s":100,
    "b":56
  },
  "cmyk":{
    "c":100,
    "m":56,
    "y":0,
    "k":44
  }
}
```

&nbsp;

HEX:#**004090** or PMS 293 C looks perfect but i noticed that it may be a little too similar to Digibyte?

So i tried a deeper shade of BLUE, which could signify stronger security and privacy for the new cryptocurrency. And it is dark as @HeyRhett's dark Plum-like color. I personally prefer a brighter blue, but i made a darker version just in case. What do you think? these are mockups and i will make SVG files if needed.. :)

Logo using [#**071867**](http://rgb.to/hex/071867) close to PMS 280 C or Reflex Blue, but darker.

![#BitcoinPrivate in Deep Reflexive BLUE](https://i.imgur.com/0Bo9UiL.png "#BitcoinPrivate in Deep Reflexive BLUE")

Colour Values as a [JSON file](http://rgb.to/save/json/color/071867):

```
{
  "hex":"#071867",
  "websafe":"#000066",
  "rgb":{
    "r":7,
    "g":24,
    "b":103
  },
  "hsl":{
    "h":229,
    "s":87,
    "l":22
  },
  "hsb":{
    "h":229,
    "s":93,
    "b":40
  },
  "cmyk":{
    "c":93,
    "m":77,
    "y":0,
    "k":60
  }
}
```

Totally open to your feedback, comments and suggestions, THANKS!

**Comment by AaronNHorvitz** [comment]
Agreed!

**Comment by AaronNHorvitz** [comment]
Agree!  The lighter version is stronger too.  It stands out more. Is it possible to have it stand straight and not tilted, to symbolize balance and stability?

**Comment by nimbosa** [comment]
Thanks for the suggestion to have it upright @AaronNHorvitz . That was sensible! But i was thinking of upward mobility when i tilted it up, in contrast to the impression of a downward movement in the original Bitcoin Logo. I want to know how others think of it. Keep those comments coming!😄

**Comment by rohan23** [comment]
Agreed. I think this is a good suggestion, much more vibrant and centered.

**Comment by AaronNHorvitz** [comment]
Thanks!  I dont think a skewed logo suggests stability and privacy.  Also, it leaves more opportunity for the logo to be used at the wrong angle.  For example, if you want to replicate it for promotional items or on literature, no one will replicate it at the same angle.  I honestly can’t take credit for this suggestion— My wife is a director of marketing, and it was her suggestion.

**Comment by tinymachine1111** [comment]
This is a great improvement. Either blue works but I think the darker "feels" a little more stable.  I'm also in the camp of preferring a straight up and down version the most.  I had that thought while looking at it and see Aaron has suggested it already.  Like Bitcoin's more professional cousin, works in a swiss private bank...wears a watch and a navy suit...keeps your secrets ;)

Thanks for doing this and putting it out there. Either way, its a nice improvement.

**Comment by Convalytics** [comment]
I think it looks better tilted forward. (to the right) Like it's driving onward. IMHO

**Comment by thePhil** [comment]
The non-upright version feels a bit nervous or too agile

**Comment by kaiansaari** [comment]
I like the first amendment, lighter and slimmer.

**Comment by BlueSilver22** [comment]
@nimbosa is it possible to the new color and have the "BP" tilted to the right instead of the left?

**Comment by elcalavera21** [comment]
Also would love to see a perfectly straight version with the more vibrant
blue!

**Comment by mrrexsocks** [comment]
Messing around with crude app on Android. Thought to use elements from a safe combination dial.  Just throwing it up for fun! http://imgur.com/qkkU0Cq

**Comment by ChocolateDon** [comment]
I feel very passionately about keeping the original color scheme, or at the very least some shade of dark blue. Like @nimbosa mentioned, the darker shade conveys a sense of privacy and security. I know this is an abstract thought process but I believe it to be a more accurate representation of the product. When considering things like design, I feel it is important to remove personal bias and consider what conveys the product it represents. I like the change in tilt so no problems with that.

**Comment by jojototh** [comment]
Thanks for suggestions, we are staying with our current logo. We need to stay consistent and became recognisable. We can update/expand our brand, but not before the fork.

**Comment by rajahat** [comment]
I prefer the original dark blue color, it hints and errs on privacy, formality, and seriousness. Conveying a message of " don't mess with me". Furthermore, I emphasize the importance of angle tilt design to magnify it's biased identity focus, as a privacy coin.

**Comment by Light-Shinchoku** [comment]
Dark blue is good.
