### ISSUE TITLE
Point of contact still refers to Zcash developers?

### ISSUE THREAD

**Issue by nimbosa** [BTCPrivate/BitcoinPrivate#45]
### Point of contact still refers to Zcash developers?
We need to put our own people here.

Places like '[**contributors and maintainers**](/BTCPrivate/BitcoinPrivate/blob/master/code_of_conduct.md) of this project' still refer to:
- Daira Hopwood (daira at z.cash)
- Sean Bowe (sean at z.cash)

**Comment by kaiansaari** [comment]
Sure, I think we're just focused on more pressing priorities right now.

**Comment by miningmining** [comment]
agreed

**Comment by nimbosa** [comment]
this was inherited from [ZCLASSIC (issue #140)](https://github.com/z-classic/zclassic/issues/140) which also lacks a point of contact

**Comment by floreslorca** [comment]
so who are the points of contact in this project? i can just change it to that
