### ISSUE TITLE
LOGO/Symbol Issue?

### ISSUE THREAD

**Issue by Cryptomike81** [BTCPrivate/BitcoinPrivate#50]
I saw in the Bitcoin Private Conference tweet that someone raised the issue that the BTCP LOGO/Symbol is being used/owned by Bitcoin Pay. Not sure if there is any concern on BTCP's end and I know there are more pressing issues, however I went ahead and put some stuff together for possible replacements. 

In most cases simplicity is better, but I added a little extra to show an array. The Z-Classic plate has the ZCL in it as well as a representation of the fork. Either way any thoughts welcome. Thanks.
![bp layout](https://user-images.githubusercontent.com/35153263/35421440-393c6b54-0211-11e8-84f6-6e556c4475d2.png)

**Comment by doerslabs** [comment]
This one truly rocks! yeah

Il 26 gen 2018 02:50, "Cryptomike81" <notifications@github.com> ha scritto:

**Comment by CoinGekko** [comment]
Love the dark blue with orange contrast! Really pops

**Comment by mesnia** [comment]
why don't we add some sort of a shield or a lock or something that represent "Private".. just a thought

**Comment by YassineEraman** [comment]
![cfbb68f1-7fe4-4e59-8cf7-4c08b34a3273](https://user-images.githubusercontent.com/20867788/35533480-9c28e91e-0535-11e8-8396-fdd00a892ef2.jpeg)
Here’s my LOGO for BTCP 

If there any issues just tell me

**Comment by mesnia** [comment]
this is awesome...

**Comment by ddelapaz** [comment]
Just my 2cents, I personally like the dark blue with the orange contrast. It looks very professional and clean.

**Comment by Concept211** [comment]
Awesome? Really? Makes the whole project look like a shitcoin. Just leave the logo alone. They're already marketing it so the branding awareness is there. You don't mess with that especially so close to the fork.

**Comment by YassineEraman** [comment]
this is only a try, not the final work so just take it easy :D

**Comment by Cryptomike81** [comment]
@Concept211 the only reason I put a new logo concept together was due to the issue that the logo they (BTCP) are using is actually someone else's logo (https://twitter.com/BitcoinPayApp) for a different business that the original owner raised issue about. I do not know if they new this originally and used it anyways or if they hired someone to create a logo and the designer decided to use that with them not knowing. Anyways the logo is basically not theirs, but I understand your concern with changing a branding logo that's already widely known.

**Comment by YassineEraman** [comment]
There's no problem in changing the logo، BTG have changed their logo just before somedays the last week

**Comment by Concept211** [comment]
Thanks for explaining that @Cryptomike81 -- I wasn't aware of that. I agree then, that's not good if it was copied so blatantly from another project. 

In all honesty, I never cared for the original BTCP logo at all when I first saw it. As a designer as well, I thought there was more that could be done with it. But since they kept going with the design in all of their marketing, I thought it was bets to leave it alone at this point because brand recognition is crucial. 

Sorry, if I came off a bit aggressive @YassineEraman - didn't mean to offend. Just didn't know the reason this thread was still active even after their website, conference, official announcements, etc.

**Comment by YassineEraman** [comment]
@concept211 ok no problem, but we just have to renew the logo as soon as possible

**Comment by jojototh** [comment]
We're staying with our logo, BitcoinPay app stole our logo which was designed by Manuel A and updated by me

**Comment by ch4ot1c** [comment]
I can confirm that this logo was designed from the BTC logo in Jan of this year. BitPay must have copied it.
