### ISSUE TITLE
BTCP for pool operators/developers

### ISSUE THREAD

**Issue by oliverw** [BTCPrivate/BitcoinPrivate#55]
Could the team provide some guidance for pool operators / developers what (if any) changes are required for existing pool/miner code already supporting ZCash/ZClassic to support the new currency?

**Comment by michaelotis** [comment]
Literally the exact same setup as ZCash/ZClassic if you're running z-nomp. Add/replace BTCP in your pool_configs and coins and point to the BTCP daemon.

**Comment by oliverw** [comment]
@michaelotis So, no founders/treasury rewards?

**Comment by michaelotis** [comment]
@oliverw No, no founders/treasury rewards.

**Comment by oliverw** [comment]
@michaelotis Two more questions if you don't mind.

1. What's the state of the code base. Is there still heavy development going on or is it more or less ready for release?

2. Will there be binary releases of the core software (daemon, cli etc.) or should pool operators prepare to build from source?
