### ISSUE TITLE
CRYPTOPIA NOT SUPPORTING ELECTRUM WALLET

### ISSUE THREAD

**Issue by Jbarnes12** [BTCPrivate/BitcoinPrivate#68]
### CRYPTOPIA NOT SUPPORTING ELECTRUM WALLET
When trying to send ZCL from cryptopia to lates electrum wallet, cryptopia says incorrect ZCL address..

**Comment by ch4ot1c** [comment]
There have been known reliability issues with Cryptopia; please retry if you have had issues.
