### ISSUE TITLE
Make Bitcoin Private Work With Hardware Wallets

### ISSUE THREAD

**Issue by heyrhett** [BTCPrivate/BitcoinPrivate#7]
We will need to register for a SLIP-44

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

I believe then we will have custom Trezor support.  Ledger Nano may require developing a custom app for the device.

**Comment by Schamnad** [comment]
I can pick up the task of developing the custom app for Ledger, is there a bounty for this?

**Comment by khajity** [comment]
50 BTCP

**Comment by heyrhett** [comment]
Ledger support almost done here:
https://github.com/KirkBallou/ledger-wallet-chrome/commit/877fad9342aded5b79d94e28f4a4b21fbb188d1d

**Comment by interbiznw** [comment]
> Ledger support almost done here:

That's not all there is to the ledger. I am in dev discord (J62) JBrutWhat said we'll discuss it at the meeting.

**Comment by busyjordy** [comment]
Can someone confirm what is the case with Segwit Addresses please. I am seeing a number of posts regarding possible complications with the fork and Segwit addresses.

**Comment by jc23424** [comment]
see here for segwit: https://github.com/BTCPrivate/BitcoinPrivate/pull/77
you'll be able to move your segwit btcp to a non-segwit output upon chain launch

**Comment by grzegorzszczecin** [comment]
@jc23424 it seems this is still broken (move segwit btcp to non-segwit output). See also issue https://github.com/BTCPrivate/BitcoinPrivate/issues/140

**Comment by BlueSilver22** [comment]
@csulmone Is this resolved?

**Comment by BlueSilver22** [comment]
support has been provided by Ledger. Pull requests made to Trezor and awaiting response. Considering this closed.
