### ISSUE TITLE
Zclassic wallet electrum not connected

### ISSUE THREAD

**Issue by amirn44** [BTCPrivate/BitcoinPrivate#71]
hi guys i send zclassic for wallet adress after that i see app is not connected!! why not connect!!

**Comment by Myran1** [comment]
Had the same Problem.
on Tools -> Network -> Server i deselected the "choose Server automatically" and it solved the problem.. for me at least on win10 x64 
![electrum-zcl-z_1 0 3-win_2018-02-18_12-06-14](https://user-images.githubusercontent.com/22836711/36351080-5b76d330-14a4-11e8-80d5-3a7162a0af17.jpg)

**Comment by ch4ot1c** [comment]
Please visit https://github.com/BTCP-community/electrum-zcl/issues to post Electrum-ZCL issues. Thanks!

**Comment by aldaw** [comment]
If someone has the same problem i solved it with this server:
electrum.zclassic.community:5002
