### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [BTCPrivate/BitcoinPrivate#73]
I would like to collaborate in the translation into Spanish? It is already done?

**Comment by ch4ot1c** [comment]
I will be going through the code and changing text from 'Zcash' and 'Zclassic' to 'Bitcoin Private'. Once this commit is made, you can get started!

Also join our Discord, we have a great localization team you can join:
https://discord.gg/C38b8A

**Comment by ch4ot1c** [comment]
Please work with Manuel on this - closing for now.
