### ISSUE TITLE
BitcoinPrivate PRICE and issues

### ISSUE THREAD

**Issue by GrannyCryptomaster** [BTCPrivate/BitcoinPrivate#79]
1 BTCP = X$
After a simple calculation, in order to keep the same profitability in BTCP mining, as is in ZCL mining, suposing the network hashrate will be the same as ZCL's, this price poped out.
ZCL block reward = 12.5 ZCL
BTCP block reward = 0.78125 BTCP 
(this is the reward propossed in the first whitepaper; they deleted the paragraf in the new whitepaper)

=> X = X $

The 2th issue with BTCP is the name. BTCP is already taken by a currency seen on stocks.exchange.
BTP is not taken, so it can be a good name for it.

The 3th issue: there will be only 700.000 coins left to mine, and after that? How the miners will be paid to keep the network running? Only from fees? They are supposed to be small.

The 4th issue: the "privacy-heroes", the Z-addresses - currently, no pool or exchange supports them for ZEC or ZCL, or at least none that I know of, so the zk-SNARKs is momentarly useless. The new sapling that is introduced with BTCP is suppose to make way for Z-address acceptance. Will see how the pools and exchanges react and what benefits the new implemantation brings.

**Comment by GrannyCryptomaster** [comment]
Missing whitepaper paragraph...
"The snapshot of Bitcoin and Zclassic is set for the first blocks timestamped after 5 PM UTC on February 28, 2018, with the fork/main-net launch occurring approximately 2 days later. After launch, there will be approximately 700,000 mineable Bitcoin Private. Remaining true to Satoshi’s vision of a low inflation coin, a starting block reward of 0.78125 Bitcoin Private has been selected. The first halving will occur after ~66,000 blocks in order to line up with the Satoshi halving scheme (around April 27, 2018). Following this, a halving will occur every 840,000 blocks. This will allow for extremely low inflation..."

**Comment by ch4ot1c** [comment]
@GrannyCryptomaster I'm going to go ahead and remove this price commentary. It is not pertinent to the development discussion. Regardless of the math / approach you've used, it is price speculation.

We will be using BTCP as our brand.

Miners will mine whichever chain they like - indeed they mine for coins until all coins are minted, and then for fees. Please see the whitepaper for further details.

Shielded addresses are indeed a feature of BTCP. Not a ton of people use them right now, but that's their prerogative. We will continue improving upon their performance.
