### ISSUE TITLE
Daemon Mainnet synching

### ISSUE THREAD

**Issue by oliverw** [BTCPrivate/BitcoinPrivate#93]
Is it possible to let btcpd start synching now? Will it use the ZClassic chain and stop accepting blocks at a certain point waiting for the BTCP mainnet to go online or will it happily sync past the hardfork block height?

**Comment by Nolaan** [comment]
you can add to your config file 
addnode=btcp.masternode.link

**Comment by jc23424** [comment]
in the next two days or so the dnsseeds listed in the repository will update with nodes that you can seed the chain from - these will be available well in advance (24-ish hours) of when mining for block reward will begin to allow miners to sync up

**Comment by OleksandrBlack** [comment]
@jc23424 @BlueSilver22 After update https://github.com/BTCPrivate/BitcoinPrivate/commit/891622875bed861ab37c758bed3b1902f15d2087
in debug.log an error **PROCESSMESSAGE: INVALID MESSAGESTART**

**Comment by oliverw** [comment]
Question: Is it supported to bootstrap a node from a ZCL blockchain copy that's not synced past the hardfork blockheight?
