### ISSUE TITLE
Bittrex > ZCL Electrum Wallet (1.0.4) done yesterday, no balance?

### ISSUE THREAD

**Issue by rtest90gmailcom** [BTCPrivate/BitcoinPrivate#98]
Bittrex > ZCL Electrum Wallet (1.0.4) done yesterday - 10 ZCLs lost ? 
Wallet Address = t1QWuGnGtUzZi8izkUiFYjqih5FiYqaMSYu

**Comment by ch4ot1c** [comment]
https://eu1.zcl-explorer.com/address/t1QWuGnGtUzZi8izkUiFYjqih5FiYqaMSYu

It isn't there; I suppose you're still waiting on Bittrex
